### Post Service API Endpoints ###
### Create Post Route
POST http://localhost:3000/v1/posts/create-post
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMzMTUxZjZlNGY2OGMxNDE5ZTg2ZjUiLCJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzY1MDQ2MzU3LCJleHAiOjE3NjUxMzI3NTd9.F54js48LxSHw7v6_k3YvresjxvaLyKd9oBuMs7Z0r60

{
 "content": "test content goes here",
 "postType": "text_with_image",
 "mediaIds": ["693558147bbcd9a43a984b0d"]
}


### Get All Posts Route
GET  http://localhost:3000/v1/posts/get-posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMzMTUxZjZlNGY2OGMxNDE5ZTg2ZjUiLCJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzY1MDQ2MzU3LCJleHAiOjE3NjUxMzI3NTd9.F54js48LxSHw7v6_k3YvresjxvaLyKd9oBuMs7Z0r60


### Get Post By Id Route
GET  http://localhost:3000/v1/posts/get-post/6931e084dceb73ff876d13c1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMwOGEzYTZjYTg5MWJmZjAxNTZiOWEiLCJ1c2VybmFtZSI6ImRldmRhZCIsImlhdCI6MTc2NDkyNzYyOSwiZXhwIjoxNzY1MDE0MDI5fQ.mlwbIu-8xjfcxb2T_AHeuffUC4KBkaskVgcN6Fu-Rso


### Delete Post By Id Route
DELETE http://localhost:3000/v1/posts/delete-post/6935582820fc82c0bfa6e632
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMzMTUxZjZlNGY2OGMxNDE5ZTg2ZjUiLCJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzY1MDQ2MzU3LCJleHAiOjE3NjUxMzI3NTd9.F54js48LxSHw7v6_k3YvresjxvaLyKd9oBuMs7Z0r60
