### Post Service API Endpoints ###
### Create Post Route
POST http://localhost:3000/v1/posts/create-post
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMzMTUxZjZlNGY2OGMxNDE5ZTg2ZjUiLCJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzY0OTU1NDg0LCJleHAiOjE3NjUwNDE4ODR9.qvTN9BCA9oVmSxEzJb3TEtsZxWFaAlXLh_b2835P79s

{
 "content": "test content goes here",
 "postType": "text_with_image",
 "mediaIds": ["693430d48059951963f563db"]
}


### Get All Posts Route
GET  http://localhost:3000/v1/posts/get-posts
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMzMTUxZjZlNGY2OGMxNDE5ZTg2ZjUiLCJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzY0OTU1NDg0LCJleHAiOjE3NjUwNDE4ODR9.qvTN9BCA9oVmSxEzJb3TEtsZxWFaAlXLh_b2835P79s


### Get Post By Id Route
GET  http://localhost:3000/v1/posts/get-post/6931e084dceb73ff876d13c1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMwOGEzYTZjYTg5MWJmZjAxNTZiOWEiLCJ1c2VybmFtZSI6ImRldmRhZCIsImlhdCI6MTc2NDkyNzYyOSwiZXhwIjoxNzY1MDE0MDI5fQ.mlwbIu-8xjfcxb2T_AHeuffUC4KBkaskVgcN6Fu-Rso


### Delete Post By Id Route
DELETE http://localhost:3000/v1/posts/delete-post/693432fe93d59b2f96af969b
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTMzMTUxZjZlNGY2OGMxNDE5ZTg2ZjUiLCJ1c2VybmFtZSI6InRlc3QxIiwiaWF0IjoxNzY0OTU1NDg0LCJleHAiOjE3NjUwNDE4ODR9.qvTN9BCA9oVmSxEzJb3TEtsZxWFaAlXLh_b2835P79s
