### User Service API Endpoints ###
### Register Route
POST http://localhost:3000/v1/users/register
content-type: application/json

{
  "firstName": "Hello",
  "lastName": "World",
  "username": "test2",
  "email": "test2@test.com",
  "password": "Abc123!"
}


### Login Route
POST http://localhost:3000/v1/users/login
content-type: application/json

{
  "email": "test2@test.com",
  "password": "Abc123!"
}


### Refresh Token Route
POST http://localhost:3000/v1/users/refresh-token
content-type: application/json

{
  "refreshToken": "0cc4bf80964a81ada00259de9c0b51d9bbe2d41690a5d9edefe53d0605c0e6b174f03ccf75006dc5"
}


### Logout Route
POST http://localhost:3000/v1/users/logout
content-type: application/json






